Add analysis to ensure deserializability
Brightspace/D2L.CodeStyle pull request #945
Opened 2024-01-18 16:53 UTC by alamarre

2024-02-02 17:54 UTC, mthjones requested changes
Still working to grok the analyzers here, but as a general comment I'd like to see all of the syntax calls replaced. Syntax trees are the wrong abstraction level here which is leading to much more complex code to review and, in the future, extend and maintain. Syntax is also more fragile to language changes (e.g. when `=>` was added for property getters). Happy to work with you to figure out symbol/operation level replacements!

2024-02-02 17:54 UTC, mthjones commented on src/D2L.CodeStyle.Analyzers/ApiUsage/Serialization/MustBeDeserializableAnalyzer.cs
> +			}
Not sure I'm fully understanding this correctly, but is this equivalent to just calling `operation.Field` to get the field symbol?

2024-02-02 17:54 UTC, mthjones commented on src/D2L.CodeStyle.Analyzers/ApiUsage/Serialization/MustBeDeserializableAnalyzer.cs
I noticed most of these actions start working with operations, but then drop down to syntax and semantic models. This is really inefficient (there's a reason all those SemanticModel methods take CancellationToken), and also makes for a lot more complex and fragile code. We should be able to do everything here with the existing operations, or by working with symbol actions. Let me know if you want to work through one together.

2024-03-21 17:39 UTC, alamarre commented
Moving to internal project

2024-03-21 17:39 UTC, closed without merging